### ISSUE TITLE
关于拉普拉斯矩阵

### ISSUE THREAD

**Issue by zcjia** [huangtinglin/NGCF-PyTorch#1]
你好，代码里的norm_adj_mat好像跟NGCF中的D^-0.5AD^-0.5不一致，但是作者的tensorflow代码好像也是这样的。

**Comment by huangtinglin** [comment]
你好，我当时也注意到了这点，作者用的是D^-1A，不过我还是按照原项目来复现。我刚提交了[normalized](https://github.com/huangtinglin/NGCF-PyTorch/blob/master/NGCF/utility/load_data.py#L124)的实现，你可以试验下，感谢！
