### ISSUE TITLE
请问原始数据集是怎么处理成训练用的txt?

### ISSUE THREAD

**Issue by inoryw** [huangtinglin/NGCF-PyTorch#10]
原始数据集(如amazon book)每行内容是 [用户 物品 评分 时间戳]
train.txt中每行是 [用户id 物品1id 物品2id 物品3id ...]
请问：
1、源数据集中用户对物品的评分如何处理？是直接忽略掉，只要有有评分就意味着发生交互吗？
2、用户对物品的交互是按8:2随机划分到训练集和数据集吗？
3、train.txt 中 每行物品的顺序是什么依据？
谢谢！

**Comment by huangtinglin** [comment]
您好！感谢您的关注。
1. 用户对物品的评分是直接忽略的，因为NGCF聚焦于对implicit feedback建模，故只考虑是否交互；
2. 是的；
3. 我个人也不太清楚，但是物品顺序应该无讲究，正确即可；
