### ISSUE TITLE
Precision值的一点疑问

### ISSUE THREAD

**Issue by Luokejin** [huangtinglin/NGCF-PyTorch#11]
在上一个问题我看到了“用户对物品的交互是按8:2随机划分到训练集和数据集”，我在切分movielen-1m也是这样切分的，然后用您的NGCF跑的时候，发现跑出来的Precision@10能达到0.5几，但movielen-1m一般这个值再好也应该只在0.15左右吧？但你的计算公式也没错... 所以我很疑惑，不知道到底哪里出问题了...

**Comment by huangtinglin** [comment]
Hi，抱歉呢我没测试过NGCF在movielen-1m上的性能，你试过其他方法在movielen-1m上的表现么，例如LightGCN或者非图卷积的算法。

**Comment by Luokejin** [comment]
> Hi，抱歉呢我没测试过NGCF在movielen-1m上的性能，你试过其他方法在movielen-1m上的表现么，例如LightGCN或者非图卷积的算法。

感谢您的回复，昨天看到你的回复后我就在lightGCN上运行了一次，好像也是这个0.5几结果... 其实包括我用在我自己的论文(gnn方法)上也是差不多是这个结果...[https://github.com/kuandeng/LightGCN](url)，另外  我看过MKR[https://github.com/hwwang55/MKR](url)以及序列推荐方法Caser的论文Precision@10都没超过0.1几， 我现在有点搞不懂了....

**Comment by huangtinglin** [comment]
抱歉迟复，我也不太确定呢，其实同一个数据集在不同场景下也不好直接比较，因为用到的loss和任务可能都不同。此外lightgcn和ngcf的评价指标计算应该都是没问题的，如果你换更大规模的movielen呢？
