### ISSUE TITLE
Question abount adjacent matrices

### ISSUE THREAD

**Issue by lemonadeseason** [huangtinglin/NGCF-PyTorch#14]
According to your paper, there are two transformation matrices in NGCF model: W1 and W2. Adjacent matrix for W1 is added with identity matrix. For W2, however, self connection is not considered.  It seems that both adjacent matrices for W1 and W2 are added with identity matrix: https://github.com/huangtinglin/NGCF-PyTorch/blob/master/NGCF/NGCF.py#L105. Looking forward to your reply : )

**Comment by huangtinglin** [comment]
Sorry for the late reply. Actually, I found that it has little effect on the performance. Besides, the author also applies the same approach in the official implementation of NGCF:

https://github.com/xiangwang1223/neural_graph_collaborative_filtering/blob/master/NGCF/NGCF.py#L194

**Comment by xizhu1022** [comment]
There is difference between the implementation of this code and original paper. The similar issue is also mentioned in offical implementation.
According to Equation 6&7 from the paper, the self-connection should be added in the forward of NGCF. The authors probably did it in the Laplacian matrix computing by msitake. If so, everything else is correct.
