### ISSUE TITLE
数据的统计

### ISSUE THREAD

**Issue by Book1996** [huangtinglin/NGCF-PyTorch#3]
你好, 我最近也在复现这篇论文. 但是我遇到了一个问题, 我所预处理的数据的统计和论文差别很大. 请问, 你有注意到吗

**Comment by huangtinglin** [comment]
> 你好, 我最近也在复现这篇论文. 但是我遇到了一个问题, 我所预处理的数据的统计和论文差别很大. 请问, 你有注意到吗

您好！我代码里运行统计的结果和论文里一致。
