### ISSUE TITLE
The example is wrong.

### ISSUE THREAD

**Issue by wandli** [huangtinglin/NGCF-PyTorch#5]
It should be `python main.py --dataset amazon-book --regs [1e-5] --embed_size 64 --layer_size [64,64,64] --lr 0.0005 --save_flag 1 --pretrain 0 --batch_size 1024 --epoch 200 --verbose 50 --node_dropout [0.1] --mess_dropout [0.1,0.1,0.1]`
not `python NGCF.py .......`

**Comment by huangtinglin** [comment]
> It should be `python main.py --dataset amazon-book --regs [1e-5] --embed_size 64 --layer_size [64,64,64] --lr 0.0005 --save_flag 1 --pretrain 0 --batch_size 1024 --epoch 200 --verbose 50 --node_dropout [0.1] --mess_dropout [0.1,0.1,0.1]`
> not `python NGCF.py .......`

Thanks! The readme is updated.
