### ISSUE TITLE
NDCG result

### ISSUE THREAD

**Issue by ghost** [huangtinglin/NGCF-PyTorch#8]
I experimented with AMAZON-BOOK data, and the NDCG result is 0.06892(At K=20), which is much higher than the paper's NDCG value (0.0261).
Is there any difference between this code and the original code?
It is questionable why the NDCG value of this code is higher than the paper value.

**Comment by huangtinglin** [comment]
Hi.
The reason is that the implementation of NDCG in the original code is different from the standard definition. You can check it in the 3rd footnote of the paper(https://arxiv.org/abs/1905.08108v2). The code is updated. Thanks!

**Comment by FinchNie** [comment]
The code doesn't look like it's been updated
