### ISSUE TITLE
请问在Amazon book数据集训练200epoch大概要多久呢？用多张GPU加速会不会对精度有影响呢？谢谢

### ISSUE THREAD

**Issue by JialeGuo** [huangtinglin/NGCF-PyTorch#9]

**Comment by huangtinglin** [comment]
您好！训练时长与所使用的显卡型号相关，目前并未尝试过多张GPU作训练，不过个人猜测应该对精度没太大影响。

**Comment by JialeGuo** [comment]
感谢回复！那单张卡训练200epoch大概要多久呢？

**Comment by JialeGuo** [comment]
另外想请问下在训练过程中打印recall，precision，hit，ndcg@20的时候为什么同步打印了@100呢？

**Comment by huangtinglin** [comment]
个人测试在2080ti下训练一个epoch差不多800s；打印@100的话没有什么别的意思，作为一种性能参考。

**Comment by JialeGuo** [comment]
我现在训练了70epoch，但离论文中结果还差很多，想问下一般需要跑完200epoch吗？那这样的话耗时需48小时，要是再尝试超参数调整是不是实验周期会很长呢？第一次了解这个任务，感谢指教~

**Comment by huangtinglin** [comment]
一般是通过early stopping的方式来结束训练，并不限定于确定个数的epoch。我个人经验而言NGCF模型本身确实需要较长的训练时长。你可以参考下性能更优越的LightGCN。
